#/templates/tls-secret.yaml
{{- if .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get .Values.ingress.tls.crtPath | b64enc }}
  tls.key: {{ .Files.Get .Values.ingress.tls.keyPath | b64enc }}
{{- end }}